### ISSUE TITLE
First 10-12 values are fine but starts giving random values after that? 

### ISSUE THREAD

**Issue by vaibhavdevnani7** [michalhol/ps2kbdlib#8] opened 2023-06-28 17:51 UTC
Have you also experienced this Issue? It starts giving scan codes like 'D', '4D', '82', '83' randomly no matter which key you press after 10-12 keystrokes or when you press keystrokes very fast in the beginning.
MCU - ESP32- WROOM
KEYBOARD - SK 2880

**Comment by tuxadecimal** [comment] 2023-11-12 06:31
Hello, I ran into this issue as well. Some ESP32 boards seems to have an issue where false or spurious calls to the interrupt handler can occur. I had one model of dev board that never did this, and one that did it all the time. This issue causes an extra interrupt to occur while the clock line is being pulsed which causes the library to get out of sync. You can fix it by changing the first line in:
 `void ICACHE_RAM_ATTR PS2Kbd::interruptHandler()` 
from: 
`if(dirOUT)
     return;` 
to:
`if(dirOUT || digitalRead(clockPin))
     return;`

This will cause it to return if the clock pin is not actually low and the issue will go away.

**Comment by cubicap** [comment] 2023-11-12 12:57
Hi, thanks for investigating the issue.

I couldn't reproduce the error and did not really have the time to go more in-depth so it really helped.

Can you please check if the issue is fixed now so I can close it?

**Comment by tuxadecimal** [comment] 2023-11-13 08:35
Doh! I had a typo, it's clkPin not clockPin. Sorry about that. I just pulled down the changes and besides the fact that I accidentally gave you the wrong variable name it does work without issue now. If you want to update that I will pull it down again to verify.

**Comment by cubicap** [comment] 2023-11-13 12:43
Ouch, completely missed that, should have checked, sorry.

Otherwise, the fix makes sense. The check probably should have been there in the first place.

**Comment by tuxadecimal** [comment] 2023-11-13 12:55
I just downloaded your updated version and it works perfectly on my board that had the issue now. Happy I could assist. Thanks for making the update!

**Comment by cubicap** [comment] 2023-11-13 13:06
Thanks for the help!

**Closed as completed by cubicap** 2023-11-13 13:06 UTC
